# Javascript Node CircleCI 2.0 configuration file

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11


jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p workspace

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: npm run bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # build nlmaps subpackages
      - run: node scripts/build -p leaflet,openlayers,googlemaps,geolocator

      # build nlmaps
      - run: node scripts/build -p nlmaps

      # run tests
      - run: node scripts/test

      #- run: mkdir -p workspace
      - run: cp -r dist workspace/
      #- run: cp package.json workspace/

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: workspace
          paths:
            - dist            

  tag_release:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "aa:c3:f1:fe:8b:79:cb:f3:79:d7:1d:77:fd:79:f9:2b"
      ### use the previous build!
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/workspace

      - run: yarn install
      - run: mv -r workspace/dist .
      - run: rmdir workspace
      - run: ls -a .
      ### bump current version number

      - run: npm --no-git-tag-version version patch
      
      ### set version number in all the package.json
      - run: npm run publish
      ### commit and tag with vx.y.z

  tagged_deploy:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
    ### get tagged version

    ### build

    ### test

    ### deploy to npm


workflows:
  version: 2
  build_and_tag:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only:
                - build-setup
      - tag_release:
          requires:
            - build_and_test  
  deploy:
    jobs:
      - tagged_deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

