# Javascript Node CircleCI 2.0 configuration file

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11


jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install the necessary packages
      - run: yarn install

      #run lerna bootstrap to install all subpackages
      - run: npm run bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # build nlmaps subpackages
      - run: node scripts/build -p leaflet,openlayers,googlemaps,geolocator

      # build nlmaps
      - run: node scripts/build -p nlmaps

      # run tests
      - run: node scripts/test
      
      # create a persistent workspace directory to store build
      - run: mkdir -p workspace
      
      # copy the build directory
      - run: cp -r dist workspace/      

      # persist the workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - dist            

  tag_release:
    <<: *defaults
    steps:
      - checkout
      # use the read/write ssh key
      - add_ssh_keys:
          fingerprints:
            - "aa:c3:f1:fe:8b:79:cb:f3:79:d7:1d:77:fd:79:f9:2b"
      # use the previous build
      - attach_workspace:          
          at: ~/repo/workspace

      # install the necessary packages
      - run: yarn install

      # get the latest build
      - run: |
          rm -r dist
          mv workspace/dist .

      # clean up after ourselves
      - run: rmdir workspace
      
      # bump the version in the root package.json
      - run: |
          VERSION=$(npm --no-git-tag-version version patch)
          MSG="Tagged version "   
          GITCOMMIT=$MSG$VERSION
          echo "export VERSION=$VERSION" >> env_file
          echo "export GITCOMMIT='$GITCOMMIT'" >> env_file
        
      # bump the version number in all the sub-package.json, using lerna
      - run: npm run publish

      - run: |
          source env_file
          git config --global user.email "github@minst.net"
          git config --global user.name "CircleCI"
          rm env_file
          rm yarn.lock
          git status
          git add -all
          git status
          git commit -m "$GITCOMMIT"
          git tag -a $VERSION -m "$GITCOMMIT"

      - run: |          
          ls -a .
          ls -a dist

      #- run: git push --tags origin

      - run: git push --tags --set-upstream origin ${CIRCLE_BRANCH}

      ### commit and tag with vx.y.z

  tagged_deploy:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
    ### get tagged version

    ### build

    ### test

    ### deploy to npm


workflows:
  version: 2
  deploy:
    jobs:
      - tagged_deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  build_and_tag:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore: /^v.*/
            branches:
              only:
                - build-setup
      - tag_release:
          requires:
            - build_and_test

